### ISSUE TITLE
try to combine other features into the model

### ISSUE THREAD

**Issue by pdan93** [MantisAI/kaggle-feedback-2021#3]
Like features mentioned here https://aclanthology.org/P19-3031v2.pdf

**Comment by nsorros** [comment]
Say we extract other features, how would we incorporate them into the model? I mean there are a couple of ways but what are your thoughts?

**Comment by pdan93** [comment]
Last time I tried this was on the other kaggle competition. I basically used the transformer last layer, concatenated it with the additional features and added some linear layers on top of those. 
I remember searching for ways of doing this back then and this was the best one I found.

**Comment by pdan93** [comment]
link to example of what I did then: https://www.kaggle.com/pdan93/clrp-features-only-model/notebook?scriptVersionId=68533491
It's good also cause it has a lof of feature extracting that we can maybe use here also

**Comment by nsorros** [comment]
Makes sense, I was thinking something similar. I could give this a try later in the week.
