### ISSUE TITLE
try to do coreference on the text before inference

### ISSUE THREAD

**Issue by pdan93** [MantisAI/kaggle-feedback-2021#4]

**Comment by nsorros** [comment]
And how would you use that information?

**Comment by pdan93** [comment]
Right, So what I thought is maybe it would be worth a try to simply do co-reference and apply it on the text. So that we give the coreferenced text to the longformer model. Intuition here being that maybe it would help him by removing some of the ambiguity?

**Comment by nsorros** [comment]
Still not 100% sure what you mean. I feel that my intuition says something similar to the cleaning idea which is that the model can model coreference internally if it needs to.
