### ISSUE TITLE
try more data augmentation

### ISSUE THREAD

**Issue by pdan93** [MantisAI/kaggle-feedback-2021#5]
What has been tried:

More classical augmentation methods like replacing words with synonyms, moving sections of the text around, etc. 
- tried this but it's clear that these kind of augmentations introduce too much noise in the data for this specific problem

Back-translation
- tried to augment with back-translation, [notebook here](https://colab.research.google.com/drive/1O_7WVYBNEhsyrZeSqiJV6bYIFgYrKoXj?usp=sharing)
- but it takes quite a bit to translate all, so I tried to keep only a percentage of the text and of that to translate only a percentage (tried a few combinations of the percentages)
- I think it may be worth it to leave a notebook to keep all text and translate all

Using GPT
- tried it a bit, but I saw quickly that it seemed to take a lot of time to generate small lengths of texts, so dropped the idea. Might be worth trying again, though I don't know exactly how you make it geneate same kind of text.

**Comment by nsorros** [comment]
Maybe let's expand as to what has been tried and what more can be tried in case I have time to pick this up

**Comment by pdan93** [comment]
expanded ;)

**Comment by nsorros** [comment]
I had an idea overnight which was to shorten the sentences that were annotated as positive and label them as negative. For example say one claim is 3 sentences, we keep only the first and in that case its negative by which I mean its not an entity that should be extracted. I was thinking it as a combination of augmentation and combatting extracting short entities. No theoretical justification whatsoever.

**Comment by pdan93** [comment]
> atting extracting short enti

Don't think I understand here completely. Can you expand a bit?

**Comment by pdan93** [comment]
> I had an idea overnight which was to shorten the sentences that were annotated as positive and label them as negative. For example say one claim is 3 sentences, we keep only the first and in that case its negative by which I mean its not an entity that should be extracted. I was thinking it as a combination of augmentation and combatting extracting short entities. No theoretical justification whatsoever.

Don't think I understand here completely. Can you expand a bit?

**Comment by pdan93** [comment]
One Idea I thought of, also related to the length of text problem was: what if we try and apply some summarization techniques to the longer ones?

**Comment by pdan93** [comment]
one other thing, in this graph (taken from a EDA notebook) we can see the frequency of the discourse types is quite unbalanced
![image](https://user-images.githubusercontent.com/2144969/156128084-8043c90f-66a0-4dc3-9dfb-e538561f3eca.png)

And that is reflected in the f1 scores for each class. The worts performing ones are Counterclaim and Rebuttal, and they are also the lowest in frequency. 

How could we try and augment the text in such a way as to increase the frequency of those?

**Comment by nsorros** [comment]
This paper https://aclanthology.org/N16-1164.pdf proposes some rules for extracting candidates. I do not fully understand the rules, they are syntactic based on pos tagging I think but the idea of filtering the data for candidates and a preprocessing step to simplify the problem could be a good one.

<img width="511" alt="Screenshot 2022-03-01 at 10 05 02 AM" src="https://user-images.githubusercontent.com/4975761/156129343-3a1a987a-14a4-4322-bf27-828a1f4b20f0.png">
